version: '3.8'
services:
  config-server:
    build: ./config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      
  eureka-server:
    build: ./eureka-server
    depends_on:
      config-server:
        condition: service_healthy
        
  admin-server:
    build: ./admin-server
    ports:
      - "8090:8090"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server
        
  api-gateway:
    build: ./api-gateway
    depends_on:
      eureka-server:
        condition: service_healthy
    ports:
      - "8080:8080"
      
  airplane-service:
    build: 
      context: ./airplane-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - config-server
      - eureka-server

  flight-service:
    build:
      context: ./flight-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - config-server
      - eureka-server

  user-info-service:
    build:
      context: ./user-info-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - config-server
      - eureka-server

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=AIRLINE
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tusty324
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 