server:
  port: 8084

spring:
  application:
    name: airplane-service
  datasource:
    url: jdbc:postgresql://localhost:5432/AIRLINE
    username: postgres
    password: Tusky324
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  boot:
    admin:
      client:
        url: http://localhost:8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true