name: Admin Server CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'admin-server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'admin-server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd admin-server
        mvn clean package -DskipTests

    - name: Build and Push Docker Image
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        cd admin-server
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
        docker build -t $DOCKER_HUB_USERNAME/admin-server:latest .
        docker push $DOCKER_HUB_USERNAME/admin-server:latest 