name: Config Server CI/CD

on:
  push:
    paths:
      - 'config-server/**'
      - '.github/workflows/config-server.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build Config Server
      run: |
        cd config-server
        mvn clean package -DskipTests
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./config-server
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/config-server:latest 