name: Airline Management System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and Test Config Server
      run: |
        cd config-server
        mvn clean verify
        
    - name: Build and Test Eureka Server
      run: |
        cd eureka-server
        mvn clean verify
        
    - name: Build and Test Airplane Service
      run: |
        cd airplane-service
        mvn clean verify
        
    - name: Build and Test Flight Service
      run: |
        cd flight-service
        mvn clean verify
        
    - name: Build and Test User Info Service
      run: |
        cd user-info-service
        mvn clean verify 