name: Airline Management System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test Config Server
      run: |
        cd config-server
        mvn clean verify
        
    - name: Build and Test Eureka Server
      run: |
        cd eureka-server
        mvn clean verify
        
    - name: Build and Test Admin Server
      run: |
        cd admin-server
        mvn clean verify
        
    - name: Build and Test Airplane Service
      run: |
        cd airplane-service
        mvn clean verify
        
    - name: Build and Test Flight Service
      run: |
        cd flight-service
        mvn clean verify
        
    - name: Build and Test User Info Service
      run: |
        cd user-info-service
        mvn clean verify

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
        docker compose version

    - name: Build Docker Images
      if: github.ref == 'refs/heads/main'
      run: |
        docker compose build
        
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Push Docker Images
      if: github.ref == 'refs/heads/main'
      run: docker compose push 