name: Airline Management System CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Config Server
      run: |
        cd config-server
        mvn clean package -DskipTests
        
    - name: Build Eureka Server
      run: |
        cd eureka-server
        mvn clean package -DskipTests
        
    - name: Build Admin Server
      run: |
        cd admin-server
        mvn clean package -DskipTests
        
    - name: Build Other Services
      run: |
        cd airplane-service
        mvn clean package -DskipTests
        cd ../flight-service
        mvn clean package -DskipTests
        cd ../user-info-service
        mvn clean package -DskipTests
        
    - name: Build Docker Images
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose build
        
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Push Docker Images
      if: github.ref == 'refs/heads/main'
      run: docker-compose push 