name: User Info Service CI/CD

on:
  push:
    paths:
      - 'user-info-service/**'
      - '.github/workflows/user-info-service.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and Test
      run: |
        cd user-info-service
        mvn clean verify
    
    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        cd user-info-service
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-info-service:latest .
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-info-service:latest 